Trigger visual test regression after create pr to development branch   release/v2.0
Billespace/Billespace pull request #12
Opened 2022-07-20 07:46 UTC by pawulonhehe

2022-07-20 12:54 UTC, polubis requested changes
Please answer comments

2022-07-20 12:54 UTC, polubis commented on billennium/package.json
> +    "react-dev-utils": "^12.0.1",
This should be dev dependency I think

2022-07-20 12:54 UTC, polubis commented on billennium/package.json
> +    "cucumber": "^6.0.7",
This too

2022-07-21 06:33 UTC, pawulonhehe commented
working, even without node-modules

2022-07-25 06:25 UTC, closed without merging